# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('plus_one', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_add_plus_one', 'Need this permission to add a plus one'),),
            },
        ),
    ]
