# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=10, null=-1),
        ),
    ]
