# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_profile_invitation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=0)),
                ('used_already', models.BooleanField(default=False)),
                ('can_add_plus_one', models.BooleanField(default=False)),
            ],
        ),
    ]
